from werkzeug.security import generate_password_hash

from database import get_db_connection


# =================================
# SKAPA USERS-TABELL
# =================================

def create_user_table():

    connection = get_db_connection()

    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'editor',
            active INTEGER NOT NULL DEFAULT 1
        )
        """
    )

    connection.commit()
    connection.close()


# =================================
# SKAPA ANVÄNDARE
# =================================

def create_user(
    username,
    password,
    role="editor"
):

    username = username.strip().lower()

    if role not in (
        "admin",
        "editor"
    ):
        raise ValueError(
            "Rollen måste vara admin eller editor."
        )

    password_hash = generate_password_hash(
        password
    )

    connection = get_db_connection()

    try:

        connection.execute(
            """
            INSERT INTO users (
                username,
                password_hash,
                role
            )

            VALUES (%s, %s, %s)
            """,
            (
                username,
                password_hash,
                role
            )
        )

        connection.commit()

    finally:

        connection.close()
