import os
import sqlite3

import psycopg
from dotenv import load_dotenv


# =================================
# INSTÄLLNINGAR
# =================================

SQLITE_PATH = "data/varn.db"

load_dotenv(".env.local")

DATABASE_URL = os.getenv("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError(
        "DATABASE_URL hittades inte i .env.local"
    )


# =================================
# ÖPPNA SQLITE
# =================================

sqlite_db = sqlite3.connect(SQLITE_PATH)
sqlite_db.row_factory = sqlite3.Row


print()
print("Ansluter till Neon...")


# =================================
# ÖPPNA NEON
# =================================

with psycopg.connect(
    DATABASE_URL,
    connect_timeout=15
) as neon_db:

    with neon_db.cursor() as cursor:

        print("✓ Ansluten till Neon")
        print()
        print("Skapar tabeller...")


        # =================================
        # TABELL: varn
        # =================================

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS varn (
                nr TEXT PRIMARY KEY,
                variant TEXT,
                byggar TEXT,
                historik TEXT,
                parkering TEXT,
                tillganglighet TEXT,
                plomberad TEXT,
                modell TEXT
            )
        """)


        # =================================
        # TABELL: users
        # =================================

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL DEFAULT 'editor',
                active INTEGER NOT NULL DEFAULT 1
            )
        """)


        # =================================
        # TABELL: change_log
        # =================================

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS change_log (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                varn_nr TEXT NOT NULL,
                username TEXT NOT NULL,
                field_name TEXT NOT NULL,
                old_value TEXT,
                new_value TEXT,
                changed_at TIMESTAMP NOT NULL
                    DEFAULT CURRENT_TIMESTAMP
            )
        """)

        neon_db.commit()

        print("✓ Tabeller klara")


        # =================================
        # HÄMTA SQLITE-DATA
        # =================================

        varn_rows = sqlite_db.execute(
            "SELECT * FROM varn"
        ).fetchall()

        user_rows = sqlite_db.execute(
            "SELECT * FROM users"
        ).fetchall()

        log_rows = sqlite_db.execute(
            "SELECT * FROM change_log"
        ).fetchall()


        print()
        print("SQLite innehåller:")
        print(f"  Värn: {len(varn_rows)}")
        print(f"  Användare: {len(user_rows)}")
        print(f"  Loggrader: {len(log_rows)}")
        print()


        # =================================
        # VÄRN
        # =================================

        print("Kopierar värn...")

        varn_data = [
            (
                row["nr"],
                row["variant"],
                row["byggar"],
                row["historik"],
                row["parkering"],
                row["tillganglighet"],
                row["plomberad"],
                row["modell"]
            )
            for row in varn_rows
        ]

        if varn_data:

            cursor.executemany(
                """
                INSERT INTO varn (
                    nr,
                    variant,
                    byggar,
                    historik,
                    parkering,
                    tillganglighet,
                    plomberad,
                    modell
                )
                VALUES (
                    %s, %s, %s, %s,
                    %s, %s, %s, %s
                )
                ON CONFLICT (nr)
                DO UPDATE SET
                    variant = EXCLUDED.variant,
                    byggar = EXCLUDED.byggar,
                    historik = EXCLUDED.historik,
                    parkering = EXCLUDED.parkering,
                    tillganglighet = EXCLUDED.tillganglighet,
                    plomberad = EXCLUDED.plomberad,
                    modell = EXCLUDED.modell
                """,
                varn_data
            )

        neon_db.commit()

        print(f"✓ {len(varn_rows)} värn kopierade")


        # =================================
        # USERS
        # =================================

        print("Kopierar användare...")

        user_data = [
            (
                row["id"],
                row["username"],
                row["password_hash"],
                row["role"],
                row["active"]
            )
            for row in user_rows
        ]

        if user_data:

            cursor.executemany(
                """
                INSERT INTO users (
                    id,
                    username,
                    password_hash,
                    role,
                    active
                )
                VALUES (%s, %s, %s, %s, %s)
                ON CONFLICT (id)
                DO UPDATE SET
                    username = EXCLUDED.username,
                    password_hash = EXCLUDED.password_hash,
                    role = EXCLUDED.role,
                    active = EXCLUDED.active
                """,
                user_data
            )

        neon_db.commit()

        print(
            f"✓ {len(user_rows)} användare kopierade"
        )


        # =================================
        # CHANGE LOG
        # =================================

        print("Kopierar ändringslogg...")

        log_data = [
            (
                row["id"],
                row["varn_nr"],
                row["username"],
                row["field_name"],
                row["old_value"],
                row["new_value"],
                row["changed_at"]
            )
            for row in log_rows
        ]

        if log_data:

            cursor.executemany(
                """
                INSERT INTO change_log (
                    id,
                    varn_nr,
                    username,
                    field_name,
                    old_value,
                    new_value,
                    changed_at
                )
                VALUES (
                    %s, %s, %s, %s,
                    %s, %s, %s
                )
                ON CONFLICT (id)
                DO NOTHING
                """,
                log_data
            )

        neon_db.commit()

        print(
            f"✓ {len(log_rows)} loggrader kopierade"
        )


        # =================================
        # KONTROLLERA NEON
        # =================================

        print()
        print("Kontrollerar Neon...")

        cursor.execute(
            "SELECT COUNT(*) FROM varn"
        )
        neon_varn = cursor.fetchone()[0]

        cursor.execute(
            "SELECT COUNT(*) FROM users"
        )
        neon_users = cursor.fetchone()[0]

        cursor.execute(
            "SELECT COUNT(*) FROM change_log"
        )
        neon_logs = cursor.fetchone()[0]


sqlite_db.close()


# =================================
# RESULTAT
# =================================

print()
print("=================================")
print("MIGRERING KLAR")
print("=================================")
print()
print(
    f"Värn:         SQLite {len(varn_rows)}"
    f" → Neon {neon_varn}"
)
print(
    f"Användare:    SQLite {len(user_rows)}"
    f" → Neon {neon_users}"
)
print(
    f"Ändringslogg: SQLite {len(log_rows)}"
    f" → Neon {neon_logs}"
)
print()
