import os
import sqlite3

from dotenv import load_dotenv
import psycopg


# =================================
# INSTÄLLNINGAR
# =================================

SQLITE_PATH = "data/varn.db"

load_dotenv(".env.local")

DATABASE_URL = os.getenv("DATABASE_URL")


if not DATABASE_URL:
    raise RuntimeError(
        "DATABASE_URL hittades inte i .env.local"
    )


# =================================
# ANSLUT TILL SQLITE
# =================================

sqlite_connection = sqlite3.connect(
    SQLITE_PATH
)

sqlite_connection.row_factory = sqlite3.Row


# =================================
# ANSLUT TILL NEON
# =================================

neon_connection = psycopg.connect(
    DATABASE_URL
)


try:

    with neon_connection.cursor() as cursor:

        # =================================
        # SKAPA TABELL: varn
        # =================================

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS varn (
                nr TEXT PRIMARY KEY,
                variant TEXT,
                byggar TEXT,
                historik TEXT,
                parkering TEXT,
                tillganglighet TEXT,
                plomberad TEXT,
                modell TEXT
            )
            """
        )


        # =================================
        # SKAPA TABELL: users
        # =================================

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT NOT NULL UNIQUE,
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL DEFAULT 'editor',
                active INTEGER NOT NULL DEFAULT 1
            )
            """
        )


        # =================================
        # SKAPA TABELL: change_log
        # =================================

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS change_log (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                varn_nr TEXT NOT NULL,
                username TEXT NOT NULL,
                field_name TEXT NOT NULL,
                old_value TEXT,
                new_value TEXT,
                changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )


        # =================================
        # KOPIERA varn
        # =================================

        varn_rows = sqlite_connection.execute(
            """
            SELECT
                nr,
                variant,
                byggar,
                historik,
                parkering,
                tillganglighet,
                plomberad,
                modell
            FROM varn
            """
        ).fetchall()


        for row in varn_rows:

            cursor.execute(
                """
                INSERT INTO varn (
                    nr,
                    variant,
                    byggar,
                    historik,
                    parkering,
                    tillganglighet,
                    plomberad,
                    modell
                )

                VALUES (
                    %s, %s, %s, %s,
                    %s, %s, %s, %s
                )

                ON CONFLICT (nr)
                DO UPDATE SET
                    variant = EXCLUDED.variant,
                    byggar = EXCLUDED.byggar,
                    historik = EXCLUDED.historik,
                    parkering = EXCLUDED.parkering,
                    tillganglighet = EXCLUDED.tillganglighet,
                    plomberad = EXCLUDED.plomberad,
                    modell = EXCLUDED.modell
                """,
                (
                    row["nr"],
                    row["variant"],
                    row["byggar"],
                    row["historik"],
                    row["parkering"],
                    row["tillganglighet"],
                    row["plomberad"],
                    row["modell"]
                )
            )


        # =================================
        # KOPIERA users
        # =================================

        user_rows = sqlite_connection.execute(
            """
            SELECT
                id,
                username,
                password_hash,
                role,
                active
            FROM users
            """
        ).fetchall()


        for row in user_rows:

            cursor.execute(
                """
                INSERT INTO users (
                    id,
                    username,
                    password_hash,
                    role,
                    active
                )

                VALUES (%s, %s, %s, %s, %s)

                ON CONFLICT (username)
                DO UPDATE SET
                    password_hash = EXCLUDED.password_hash,
                    role = EXCLUDED.role,
                    active = EXCLUDED.active
                """,
                (
                    row["id"],
                    row["username"],
                    row["password_hash"],
                    row["role"],
                    row["active"]
                )
            )


        # =================================
        # KOPIERA change_log
        # =================================

        change_rows = sqlite_connection.execute(
            """
            SELECT
                id,
                varn_nr,
                username,
                field_name,
                old_value,
                new_value,
                changed_at
            FROM change_log
            """
        ).fetchall()


        for row in change_rows:

            cursor.execute(
                """
                INSERT INTO change_log (
                    id,
                    varn_nr,
                    username,
                    field_name,
                    old_value,
                    new_value,
                    changed_at
                )

                VALUES (
                    %s, %s, %s, %s,
                    %s, %s, %s
                )

                ON CONFLICT (id)
                DO NOTHING
                """,
                (
                    row["id"],
                    row["varn_nr"],
                    row["username"],
                    row["field_name"],
                    row["old_value"],
                    row["new_value"],
                    row["changed_at"]
                )
            )


    neon_connection.commit()


    print()
    print("=================================")
    print("MIGRERING KLAR!")
    print("=================================")
    print()
    print(
        f"Värn: {len(varn_rows)}"
    )
    print(
        f"Användare: {len(user_rows)}"
    )
    print(
        f"Ändringsloggar: {len(change_rows)}"
    )
    print()


except Exception as error:

    neon_connection.rollback()

    print()
    print("MIGRERING MISSLYCKADES")
    print(error)
    print()

    raise


finally:

    sqlite_connection.close()
    neon_connection.close()
